# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7190cfcd30255357a48ed82287cfde411964ff186ae8e8f584e7d1a62ebd377d487bf6df93b09b0cf63d72c0d214c3a92799138c581bec634f00d7532f25d5ca

test:
  secret_key_base: e18a3b932ea89488987f156b877e705c3cddd59005e5473ed2ccc174d19f28112f82da578fc0330757e04527ea1ce2139d227ed508c41209c2e7771b3d5f462e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
